### ISSUE TITLE
Incorrect parameters in README for command-line execution

### ISSUE THREAD

**Issue by jindrichmynarz** [yyz1989/NoSPA-RDF-Data-Cube-Validator#1]
README.md instructs the users to use the following to run the validator on the command line:

``` bash
java -jar nospa-rdf-data-cube-validator-0.9.9-jar-with-dependencies.jar your_cube_file.ttl file_format_in_uppercase
```

However, if you run the validator in this way (e.g., `java -jar nospa-rdf-data-cube-validator-0.9.9-jar-with-dependencies.jar your_cube_file.ttl TURTLE`), the validator throws the error `Validator type is not supported`. Instead of file format the validator type must be provided as the last parameter (i.e., `NOSPA` or `SPARQL`), as is clear from the [source code](https://github.com/yyz1989/NoSPA-RDF-Data-Cube-Validator/blob/b48b3ae98157506ad3938b06a7716b8803d42faf/src/main/java/cn/yyz/nospa/validator/Main.java#L45). README should be updated to reflect this accordingly.

**Comment by yyz1989** [comment]
Hey Jindřich, thanks a lot for pointing out! I will update it now.
