### ISSUE TITLE
custom report results folder?

### ISSUE THREAD

**Issue by seralf** [yyz1989/NoSPA-RDF-Data-Cube-Validator#2]
Hi

I didn't find any way to save the reports under a specific folder, by means of using for example a dedicated command-line argument. Is there a way to accomplish this? Or can you suggest me where to start to add it from Java?

thank you in advance

**Comment by yyz1989** [comment]
Hi,

In fact the "reports" are logs generated by log4j, which can be configured in /src/main/resources/log4j.xml. My apologies for this confusion. I have plans to update this tool, but I was constantly busy. I will try to continue the development when I get some free time. 

Thanks a lot for the attention.

Regards,
Yang

**Comment by seralf** [comment]
hi thank you for the tip! I supected there was log4j, and tried to change
the saved files, but without success, have you some suggestion on this?

thank you

2016-05-28 11:38 GMT+02:00 Yang notifications@github.com:

**Comment by yyz1989** [comment]
Sure, in log4j.xml file there are two appenders named "log" and "result". There is one line like

```
<param name="file" value="${user.dir}/validation_result_${current.timestamp}.md"/>
```

for each appender, declaring the log file output path. You can change it as you wish. "${user.dir}" is the working directory. You can use "${user.home}" to get the home directory for the user, or just use an absolute path for any location.

**Comment by seralf** [comment]
thank you for the answer, sorry for replying so late: I didn't have the chance to test your suggestion before! :-)
